#+AUTHOR: esac <esac-io@tutanota.com>
#+PROPERTY: header-args :tangle no

* Introduction

  This repository is just a place to hold the Org files
  that compose the content of my personal blog which it's called
  =Hidden-ones=.

* Overview

  For a long time I desired to start a blog to write about anything of
  my interest which is basically science, and force myself to finish the
  parts of the research that are forever in progress.

  Of course, I have another reasons to do so: practice writing, learn
  more about the English language as a whole and have a online
  presence to spread the material.

  With the help of a very craft Emacs's package called
  =org-static-blog= it's possible to accomplish this using the
  beloved  =org-mode= a tool that I already use in a daily basis to
  conduct the process of taking notes from the sources in question
  and structure the information in a concise and organized
  way, making this setup very practical and direct.

  The static =html= files are generated by =org-mode= export/publish
  functionalities the content are extracted from the =org= files and
  =org-static-blog= provides a easy way to organize the content in
  a blog format.

* Dependencies

  - Org-mode
  - Org-static-blog

* Setup

  The whole setup is very simple, after installation of the =org-static-blog=
  package was complete will be onlye necessary to have a directory
  tree as the described below:

  #+BEGIN_SRC sh



  #+END_SRC

  The main values used for =org-static-blog= variables are:

  #+BEGIN_SRC emacs-lisp

  ;; url of the blog.
  (customize-set-variable
    'org-static-blog-publish-url "https://esac-io.github.io/")

  ;; directory where published HTML files are stored
  (customize-set-variable
   'org-static-blog-publish-directory
   (expand-file-name
    (concat user-emacs-directory "blog/site/esac-io.github.io")))

  ;; directory where published ORG files are stored
  (customize-set-variable
   'org-static-blog-posts-directory
   (expand-file-name
    (concat user-emacs-directory "blog/posts/")))

  ;; directory where unpublished ORG files are stored.
  (customize-set-variable
   'org-static-blog-drafts-directory
   (expand-file-name
    (concat user-emacs-directory "blog/posts/drafts/")))

  ;; use preview versions of posts on multipost pages
  (customize-set-variable 'org-static-blog-use-preview t)

  ;; when preview is enabled, convert <h1> to <h2> for the previews
  (customize-set-variable 'org-static-blog-preview-convert-titles t)

  ;; the HTML appended to the preview if some part of the post is hidden
  (customize-set-variable 'org-static-blog-preview-ellipsis "(...)")

  #+END_SRC

  For more information see the org-static-blog manual[2].

* References

  1. https://orgmode.org/manual/Publishing.html
  2. https://github.com/bastibe/org-static-blog

* LICENSE
  MIT

* EOF
  Writing is an exploration. You start from nothing
  and learn as you go.
  | E. L. Doctorow |
