#+AUTHOR: esac <esac-io@tutanota.com>
#+PROPERTY: header-args :tangle no

* Introduction

  This repository is just a place to hold the =org= files
  that compose the content of my personal blog which it's called
  =Hidden-ones=.

* Overview

  For a long time I desired to start a blog to write about anything of
  my interest which is basically all human knowledge, and force myself
  to finish parts of the researches that are forever in progress.

  Of course, I have another reasons to do so: practice writing, learn
  more about the English language as a whole, have a online
  presence to spread the material and be open to receive criticism
  from the community.

  With the help of a very craft Emacs package called
  =org-static-blog= it's possible to accomplish this using the
  beloved =org-mode= a tool that I use massively in my daily basis to
  conduct the process of investigation, which means:
  Taking notes from the accessed sources, analyse it and
  structure all the generated information in a concise form,
  making this setup precious, direct and practical.

  The static =html= files are generated by =org-mode= export/publish
  functionalities the contents are extracted from the =org= files and
  =org-static-blog= provides ways to organize the data in a web-blog
  format.

* Dependencies

  - Org-mode
  - Org-static-blog

* Setup

  The whole setup it's simple as it can be, after the
  installation of =org-static-blog= package was completed,
  will be only necessary to have a directory tree as the
  described below:

  #+BEGIN_SRC sh

  .
  ├── assets
  ├── html
  │   ├── header.html
  │   ├── postamble.html
  │   ├── preamble.html
  │   └── static
  │       ├── cover.jpg
  │       ├── favicon.ico
  │       ├── lambda.png
  │       └── style.css
  ├── pages
  │   ├── about.org
  │   └── projects.org
  ├── posts
  │   └── drafts
  └── site

  #+END_SRC

  The main values used for =org-static-blog= variables are:

  #+BEGIN_SRC emacs-lisp

  ;; url of the blog.
  (customize-set-variable
    'org-static-blog-publish-url "https://esac-io.github.io/")

  ;; directory where published HTML files are stored
  (customize-set-variable
   'org-static-blog-publish-directory
   (expand-file-name
    (concat user-emacs-directory "blog/site/esac-io.github.io")))

  ;; directory where published org files are stored
  (customize-set-variable
   'org-static-blog-posts-directory
   (expand-file-name
    (concat user-emacs-directory "blog/posts/")))

  ;; directory where unpublished org files are stored.
  (customize-set-variable
   'org-static-blog-drafts-directory
   (expand-file-name
    (concat user-emacs-directory "blog/posts/drafts/")))

  ;; use preview versions of posts on multipost pages
  (customize-set-variable 'org-static-blog-use-preview t)

  ;; when preview is enabled, convert <h1> to <h2> for the previews
  (customize-set-variable 'org-static-blog-preview-convert-titles t)

  ;; the html appended to the preview if some part of the post is hidden
  (customize-set-variable 'org-static-blog-preview-ellipsis "(...)")

  #+END_SRC

  For more information see the org-static-blog manual[2].

* References

  1. https://orgmode.org/manual/Publishing.html
  2. https://github.com/bastibe/org-static-blog

* LICENSE
  MIT

* EOF
  Writing is an exploration. You start from nothing
  and learn as you go.
  | E. L. Doctorow |
