#+title: About
#+author: esac
#+filetags: About

* About

  Well, everyone knows how hard writing can be (even more challenging
  using a non-native language), so this blog was created as an attempt
  to improve this skill, as a side effect, add a little bit more
  information on the data sea called =VIRTUALITY=.

  =Virtual= interfaces are already the main bridges used to access the present,
  understand the past and unveil the future, all beings, all things,
  interlinked. Oh, sorry, lost my train of thought here...

  Although, the intent is to write about anything that sparkles
  interest, the main focus will be on the following subjects:

  #+BEGIN_EXAMPLE
  Algorithms, BSD, Computer History, Data-Oriented Design, Functional Programming,
  Emacs, Elisp, Mathematics and Philosophy.
  #+END_EXAMPLE

  The name =Hidden-ones= is just a humble homage to all
  the twisted =1's= forgotten inside our memories.

* Contact

  - [[mailto:esac-io@tutanota.com][esac-io@tutanota.com]]

* Links

  - [[https://github.com/esac-io][esac-io.git]]
  - [[https://github.com/esac-io/hidden-ones][hidden-ones.git]]

* WHOMI

  At this point doesn't matter, does it?

  Let's leave the work do the talking, beware though,
  the posts contents comes from a disturbed/disruptive
  mind and can be to much for some people, be careful,
  but be happy :)

* Mantra

  #+BEGIN_SRC

  Litany Against Fear

  I must not fear.
  Fear is the mind-killer.
  Fear is the little-death that brings total obliteration.
  I will face my fear.
  I will permit it to pass over me and through me.
  And when it has gone past I will turn the inner eye to see its path.
  Where the fear has gone there will be nothing.
  Only I will remain.

  #+END_SRC

* EOF

  #+BEGIN_SRC
  Highly organized research is guaranteed to produce nothing new.
  #+END_SRC

| Franklin Patrick Herbert Jr. |
