#+TITLE: Projects
#+AUTHOR: lambdart
#+EMAIL: lambdart@protonmail.com
#+FILETAGS: projects
#+OPTIONS: toc:t |:t *:t

* VLM

  Just another *Emacs* configuration written in the literate
  programming format with the help of [[https://orgmode.org][org-mode]], that has a simple
  goal - be just a configuration file, i.e, set custom values and
  hooks for the libraries of interest.

  Some people (including me) have started to refer to Emacs as a LISP MACHINE.
  It is not strictly a lisp machine because, clearly, it is a software
  program and not a physical computer, but as that line starts to blur
  it seems like a useful epithet for *Emacs*, because these days it
  looks more and more like an =OS=.

  https://github.com/lambdart/vlm

* Cannon

  An *Elisp* library that mimics the beloved [[https://tools.suckless.org/dmenu/][Dmenu]] to launch =Unix=
  utilities using the *Emacs* command prompt interface, a.k.a, the
  =minibuffer=.

  The project’s name itself is a joke about launching
  =Chrome= web browser inside *Emacs/Exwm* - a heavy metal ball that
  causes nightmares.

  https://github.com/lambdart/cannon

* Lazy-Load

  An *Elisp* library that provides and easy automatic way to generate
  load definitions =autoloads= from pre-configured directories, i.e,
  other libraries, accelerating *Emacs* initialization process.

  | Lazy-Load | (emacs-init-time)   |
  | No        | 4.871672671 seconds |
  | Yes       | 0.489159734 seconds |

  https://github.com/lambdart/lazy-load

* EOF

  #+BEGIN_SRC
  What is a man? A Miserable little pile of secrets!
  #+END_SRC

