#+title: Hello World
#+date: <2020-06-25 16:26>
#+filetags: emacs blog org-mode org-static-blog

* Introduction

  This is just a hello world type of blog post to explain and
  test the capabilities of =org-static-blog=, I also want to
  provide a template for future articles (or blog posts) to be
  follow in the next adventures.

  This article will be dived in six sections. The first
  one called 'The Setup' will explains how to install the
  software used and a little bit of rationalization on
  why they were chosen.

  After that, in 'The Files' section, we will dissect the static
  =html/css= files used by =org-mode= to organize and display
  the information ( in the weblog format) generated by any research.

  On 'The Apparence' will be discussed design decisions on the
  perspective of someone who doesn't no much about =CSS=
  and hate the world wide web technologies.

  In the 'The Features' sections, we will get more context
  on what if offered by the Emacs's packages in question
  (=org-mode= and =org-static-blog=) and what can be achieved
  with them, providing examples for each encounter feature.
  A small discussion why is so important to
  ways strive for simplicity and minimalism.

  As expected the last section 'The Conclusion' will be
  summarized what was learned and a small discussion on
  why is so important to strive for simplicity, optimization and
  minimalism.

  The references will be listed on the 'References', and will be the
  final section.

* The Setup
* The Files
* The Apparence
* The Features
* The Functions
* The Conclusion
* References
