#+title: Hello World
#+date: <2020-06-25 16:26>
#+filetags: emacs blog org-mode org-static-blog

* Introduction

  This is just a =hello world= type of blog post to explain and
  test the capabilities of =org-static-blog=, I also want to
  provide a template (as a reference for others and myself)
  to address the process of writing new articles (or blog posts).

  The blog post (or article) will be dived in six sections.
  The first one called 'The Setup' will explains how to install the
  software used and a little rationalization on why they were chosen.

  After that, in 'The Files' section, we will dissect the static
  =html/css= files used by =org-mode= export/publish features.

  On 'The Apparence' will be discussed the design decisions on the
  perspective of someone who doesn't know much about =CSS=
  and hate (with vigor) the world wide web front-end
  technologies.

  In the 'The Features' sections, we will get more context
  on what is offered by the Emacs's packages in question
  (=org-mode= and =org-static-blog=) and what can be achieved
  with them, providing examples for each encounter feature.

  The created functions to make everything more practical and
  dynamic are described on 'The Functions' section.

  As expected, in the section 'The Conclusion' will be
  summarized what was learned and a small discussion on
  why is so important to strive for simplicity, optimization
  and minimalism.

  The links will be listed in the 'References' it is the final section.

* The Setup
* The Files
* The Apparence
* The Features
* The Functions
* The Conclusion
* References
