#+TITLE: Virtuality
#+DATE: <2020-12-02 Wed>
#+AUTHOR: lambdart
#+EMAIL: lambdart@protonmail.com
#+TAGS: Virtuality Philosophy Manifesto
#+OPTIONS: toc:nil |:t *:t num:nil tags:t prop:t author:t title:t

  -----
  <2020-12-02 Wed>
  -----

  *Life is just a dream you know...*

  With the decline and eminent collapse of western civilization,
  a clear horizon is blossoming, it's almost palpable, alive, breath
  taking, expanding itself in a overwhelming fast pace, taking form,
  nothing and everything at the same time, existential detachment!

  *You can't keep up with it, tick-tack-tick-tack-tick-tack...*

  It's all happening in front of our eyes: =Virtual= interfaces are
  already the main bridges used to access the present, understand the
  past and unveil the future, all beings, all things, interlinked. An
  unstoppable force that will obliterate every obsolete obstacle in
  its path. Abruptly dynamic and merciless by nature.

  *You are just an obsolete meat machine...*

  Without bounds, without time, absorbing everything, like a black hole
  open in the beautiful blue sky. An singularity that sees
  divisions of knowledge imposed by 'modern' society as fundamental
  mistakes for the ones that has no say or the minimal understanding
  on the self education process and the new possibilities that arrives
  with it...

  *You can't write a simple recursive function to explain life...*

  The more old we get, the world narrows down the paths
  that can be taken, it's simple - we will not break free - we'll all
  die in the glimpse of the *new born era* and immortalized as the
  most fraudulent generation in bits of history...

* EOF

  #+BEGIN_EXAMPLE
  Just a whisper... I hear it in my ghost.
  #+END_EXAMPLE

